"""
Verify that the Key Finding contract is actually being enforced.

Two modes, because the usual question is "did my change take effect?" and the
answer depends on whether the running worker reloaded the new code:

  --text "..."     Check a literal sentence. Needs no database. Use this to
                   confirm the guard logic itself behaves as expected.

  (no args)        Read stored reports from MongoDB and, for each, print the
                   prompt contract version it was generated with and whether
                   its Key Finding complies. A report whose
                   `ai_contract_version` differs from the current one was
                   produced by an older prompt and needs regenerating; a report
                   stamped with the CURRENT version that still fails the
                   contract means the guard did not run, which points at a
                   stale worker process rather than the prompt.

Usage
-----
    python -m backend.scripts.verify_key_finding --text "Hero must address ..."
    python -m backend.scripts.verify_key_finding
    python -m backend.scripts.verify_key_finding --survey-id <id>
"""
from __future__ import annotations

import argparse
import asyncio
import sys
from typing import Any, Dict, List

from backend.analytics_module.src.ai.key_finding_guard import (
    build_fallback_key_finding,
    validate_key_finding,
)

GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
DIM = "\033[2m"
OFF = "\033[0m"


def _report_line(ok: bool, label: str) -> str:
    mark = f"{GREEN}PASS{OFF}" if ok else f"{RED}FAIL{OFF}"
    return f"  [{mark}] {label}"


def check_text(text: str, attributes: List[str], modules: List[str]) -> bool:
    print(f"\n{DIM}Key Finding:{OFF} {text}")
    verdict = validate_key_finding(
        text, measured_attributes=attributes, modules_used=modules
    )
    print(_report_line(verdict.ok, "contract compliance"))
    for reason in verdict.reasons:
        print(f"        {YELLOW}-{OFF} {reason}")
    return verdict.ok


async def check_stored(survey_id: str | None) -> int:
    from backend.database import db
    from backend.services.analytics_service import _ai_contract_version

    current = _ai_contract_version()
    print(f"Current prompt contract: {GREEN}{current}{OFF}\n")

    col = db.get_collection("survey_reports")
    if col is None:
        print(f"{RED}No database connection.{OFF} Start MongoDB, or use --text to "
              f"check the guard logic offline.")
        return 2

    query: Dict[str, Any] = {"survey_id": survey_id} if survey_id else {}
    reports = await col.find(
        query,
        {
            "survey_id": 1, "project_name": 1, "ai_contract_version": 1,
            "insights.executive_summary": 1, "charts": 1, "brands": 1,
        },
    ).sort("generated_at", -1).to_list(200)

    if not reports:
        print("No stored reports found.")
        return 0

    stale = 0
    failing = 0

    for rep in reports:
        name = rep.get("project_name") or "(unnamed)"
        version = rep.get("ai_contract_version") or "unstamped (pre-guard)"
        summary = ((rep.get("insights") or {}).get("executive_summary")) or ""

        print("=" * 74)
        print(f"{name}  {DIM}({rep.get('survey_id')}){OFF}")
        print(f"  contract: {version}")

        if version != current:
            stale += 1
            print(f"  {YELLOW}=> generated by an older prompt; regenerate this report{OFF}")

        verdict = validate_key_finding(summary)
        print(f"  finding : {summary[:110] or '(empty)'}")
        print(_report_line(verdict.ok, "contract compliance"))
        for reason in verdict.reasons[:4]:
            print(f"        {YELLOW}-{OFF} {reason}")

        if not verdict.ok:
            failing += 1
            if version == current:
                print(f"  {RED}=> stamped CURRENT yet non-compliant: the guard did not run.{OFF}")
                print(f"  {RED}   Restart the backend worker so it loads the new code.{OFF}")
            fallback = build_fallback_key_finding(
                target_brand=(rep.get("brands") or [""])[0],
                charts=rep.get("charts") or [],
            )
            print(f"  {DIM}guard would emit:{OFF} {fallback[:150]}")

    print("=" * 74)
    print(f"{len(reports)} report(s): {failing} non-compliant, {stale} on an older prompt.")
    return 1 if failing else 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify Key Finding contract enforcement.")
    parser.add_argument("--text", help="Check a literal sentence; no database needed.")
    parser.add_argument("--survey-id", help="Limit the stored-report check to one survey.")
    parser.add_argument(
        "--attributes", default="",
        help="Comma-separated measured attributes, for use with --text.",
    )
    parser.add_argument(
        "--modules", default="",
        help="Comma-separated modules that ran, for use with --text.",
    )
    args = parser.parse_args()

    if args.text:
        attributes = [a.strip() for a in args.attributes.split(",") if a.strip()]
        modules = [m.strip() for m in args.modules.split(",") if m.strip()]
        ok = check_text(args.text, attributes, modules)
        if not ok:
            print(f"\n{DIM}The guard would replace this sentence with a "
                  f"chart-derived one at generation time.{OFF}")
        return 0 if ok else 1

    return asyncio.run(check_stored(args.survey_id))


if __name__ == "__main__":
    sys.exit(main())
